@!include ../commons.style
@startuml "class diagram"
interface Document {
    + titre(): String
    + taille(): int
}
class Mémoire implements Document {
    - titre: String
    + {static} this(titre: String, chapitres: List<Chapitre>)
    + titre(): String
    + taille(): int
}
class Chapitre implements Document {
    - titre: String
    - pages: String[*]
    + {static} this(titre: String, pages: String[*])
    + titre(): String
    + taille(): int
}
Mémoire *--> "- cs *" Chapitre
@enduml