@!include ../commons.style
@startuml "sequence diagram"
participant "mémoireAlice: Mémoire" as mA
participant "ci: Chapitre" as ci
[-> mA: taille()
activate mA
    mA -> mA : t = 0
    loop ci in cs
        mA -> ci: taille()
        activate ci
        mA <-- ci: ti
        deactivate ci
        mA -> mA : t = t + ti
    end
[<-- mA: t
deactivate mA
@enduml
