plugins {
    id 'java'
    id 'application'
}

repositories {
    mavenCentral()
}

dependencies {
    testImplementation 'org.junit.jupiter:junit-jupiter:5.9.3'
    testRuntimeOnly 'org.junit.platform:junit-platform-launcher:1.9.3'
    implementation 'io.vavr:vavr:0.10.4'
}

application {
    mainClass = 'org.example.App' // adapte si besoin
}

test {
    useJUnitPlatform() // réservé à JUnit 5
}
